name: Build and deploy Python FastAPI app to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create requirements.txt for Azure
        run: |
          pip freeze > requirements.txt
          echo "✅ Requirements.txt created"

      - name: Prepare deploy artifact
        run: |
          rm -rf deploy
          mkdir -p deploy
          # Copy all necessary files
          cp -r . deploy/
          cp ../db_control deploy/ -r
          # Remove unnecessary files
          rm -rf deploy/venv
          rm -rf deploy/__pycache__
          find deploy -name "__pycache__" -type d -exec rm -rf {} + || true
          find deploy -name "*.pyc" -delete || true
          echo "📦 Contents of deploy:"
          ls -la deploy

      - name: Zip deploy contents
        run: |
          cd deploy
          zip -r ../deploy.zip .
          cd ..
          echo "✅ deploy.zip created"
          unzip -l deploy.zip | head -n 30

      - name: Upload deploy artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deploy.zip
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-1-node-oshima58-backend'
          slot-name: 'Production'
          package: ./deploy.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BACKEND }}
