name: Deploy Python FastAPI to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test connection
        run: |
          python test_connection.py

      - name: Create deployment package
        run: |
          mkdir -p deploy
          # Copy necessary files and directories explicitly
          cp app.py deploy/
          cp -r db_control deploy/
          cp -r backend deploy/ || true
          cp requirements.txt deploy/
          cp startup.sh deploy/ || true
          cp test_connection.py deploy/ || true
          cp .env deploy/ || true
          cp *.pem deploy/ || true
          echo "📦 Deployment package created"
          ls -la deploy

      - name: Zip deployment package
        run: |
          cd deploy
          zip -r ../deploy.zip .
          cd ..
          echo "✅ deploy.zip created"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deploy.zip
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Azure Login
        uses: azure/login@v2
        with:
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-1-py-oshima58'
          slot-name: 'Production'
          package: ./deploy.zip
